{
  getBlocks(
    where: {
      height: {
        gt: 0 # Greater than 1989.
        lt: 1000 # Less than 2001.
      }
    }
  ) {
    # Fields to retrieve for each block.
    hash # The unique hash identifier of the block.
    height # The block's height in the blockchain.
    time # Timestamp when the block was created.
    total_txs # Total number of transactions up to this block.
    num_txs # Number of transactions in the block.
    total_txs # Number of total transactions.
  }
}
